# Generated by Django 4.2.4 on 2023-10-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_author_remove_blogpost_author_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
