# Generated by Django 4.2.4 on 2023-10-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plan_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
