# Generated by Django 4.2.4 on 2024-01-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=30)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('date', models.DateField()),
            ],
        ),
    ]
