# Generated by Django 4.2.4 on 2023-09-18 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ForexContentApp', '0002_alter_signal_risk_disclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystep',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailystep',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tradebreakdown',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradebreakdown',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
